2024-09-24 14:39:13.2739 CW.Common.Logs.NLogHelper.ErrorLog Error: 
【描述】：Index was outside the bounds of the array.
【堆栈】：at SqlSugar.UpdateableProvider`1.SetColumns(Expression`1 columns)
   at CW.Api.Services.LoginService.EditAccount(String openId, Int32 bay) in D:\work\crazy-workers-net.git\CW.Api\Services\LoginService.cs:line 52
   at CW.Api.Controllers.LoginController.Login(LoginModel model) in D:\work\crazy-workers-net.git\CW.Api\Controllers\LoginController.cs:line 56
   at lambda_method484(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) 
  ResourceInvoker.Next => GlobalExceptionsFilter.OnException => NLogHelper.ErrorLog
2024-09-24 14:39:53.7288 CW.Common.Logs.NLogHelper.ErrorLog Error: 
【描述】：Index was outside the bounds of the array.
【堆栈】：at SqlSugar.UpdateableProvider`1.SetColumns(Expression`1 columns)
   at CW.Api.Services.LoginService.EditAccount(String openId, Int32 bay) in D:\work\crazy-workers-net.git\CW.Api\Services\LoginService.cs:line 52
   at CW.Api.Controllers.LoginController.Login(LoginModel model) in D:\work\crazy-workers-net.git\CW.Api\Controllers\LoginController.cs:line 56
   at lambda_method484(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) 
  ResourceInvoker.Next => GlobalExceptionsFilter.OnException => NLogHelper.ErrorLog
2024-09-24 14:40:49.0653 CW.Common.Logs.NLogHelper.ErrorLog Error: 
【描述】：Index was outside the bounds of the array.
【堆栈】：at SqlSugar.UpdateableProvider`1.SetColumns(Expression`1 columns)
   at CW.Api.Services.LoginService.EditAccount(String openId, Int32 bay)
   at CW.Api.Controllers.LoginController.Login(LoginModel model)
   at lambda_method484(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) 
  ResourceInvoker.Next => GlobalExceptionsFilter.OnException => NLogHelper.ErrorLog
2024-09-24 14:41:34.8830 CW.Common.Logs.NLogHelper.ErrorLog Error: 
【描述】：Index was outside the bounds of the array.
【堆栈】：at SqlSugar.UpdateableProvider`1.SetColumns(Expression`1 columns)
   at CW.Api.Services.LoginService.EditAccount(String openId, Int32 bay) in D:\work\crazy-workers-net.git\CW.Api\Services\LoginService.cs:line 52
   at CW.Api.Controllers.LoginController.Login(LoginModel model) in D:\work\crazy-workers-net.git\CW.Api\Controllers\LoginController.cs:line 56
   at lambda_method484(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) 
  ResourceInvoker.Next => GlobalExceptionsFilter.OnException => NLogHelper.ErrorLog
2024-09-24 14:42:46.1599 CW.Common.Logs.NLogHelper.ErrorLog Error: 
【描述】：Index was outside the bounds of the array.
【堆栈】：at SqlSugar.UpdateableProvider`1.SetColumns(Expression`1 columns)
   at CW.Api.Services.LoginService.EditAccount(String openId, Int32 bay) in D:\work\crazy-workers-net.git\CW.Api\Services\LoginService.cs:line 52
   at CW.Api.Controllers.LoginController.Login(LoginModel model) in D:\work\crazy-workers-net.git\CW.Api\Controllers\LoginController.cs:line 56
   at lambda_method484(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) 
  ResourceInvoker.Next => GlobalExceptionsFilter.OnException => NLogHelper.ErrorLog
2024-09-24 14:42:56.0803 CW.Common.Logs.NLogHelper.ErrorLog Error: 
【描述】：Index was outside the bounds of the array.
【堆栈】：at SqlSugar.UpdateableProvider`1.SetColumns(Expression`1 columns)
   at CW.Api.Services.LoginService.EditAccount(String openId, Int32 bay) in D:\work\crazy-workers-net.git\CW.Api\Services\LoginService.cs:line 52
   at CW.Api.Controllers.LoginController.Login(LoginModel model) in D:\work\crazy-workers-net.git\CW.Api\Controllers\LoginController.cs:line 56
   at lambda_method484(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) 
  ResourceInvoker.Next => GlobalExceptionsFilter.OnException => NLogHelper.ErrorLog
2024-09-24 14:43:15.8065 CW.Common.Logs.NLogHelper.ErrorLog Error: 
【描述】：Index was outside the bounds of the array.
【堆栈】：at SqlSugar.UpdateableProvider`1.SetColumns(Expression`1 columns)
   at CW.Api.Services.LoginService.EditAccount(String openId, Int32 bay) in D:\work\crazy-workers-net.git\CW.Api\Services\LoginService.cs:line 52
   at CW.Api.Controllers.LoginController.Login(LoginModel model) in D:\work\crazy-workers-net.git\CW.Api\Controllers\LoginController.cs:line 56
   at lambda_method484(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) 
  ResourceInvoker.Next => GlobalExceptionsFilter.OnException => NLogHelper.ErrorLog
2024-09-24 14:43:51.3051 CW.Common.Logs.NLogHelper.ErrorLog Error: 
【描述】：Index was outside the bounds of the array.
【堆栈】：at SqlSugar.UpdateableProvider`1.SetColumns(Expression`1 columns)
   at CW.Api.Services.LoginService.EditAccount(String openId, Int32 bay) in D:\work\crazy-workers-net.git\CW.Api\Services\LoginService.cs:line 52
   at CW.Api.Controllers.LoginController.Login(LoginModel model) in D:\work\crazy-workers-net.git\CW.Api\Controllers\LoginController.cs:line 56
   at lambda_method484(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) 
  ResourceInvoker.Next => GlobalExceptionsFilter.OnException => NLogHelper.ErrorLog
2024-09-24 14:54:57.0711 CW.Common.Logs.NLogHelper.ErrorLog Error: 
【描述】：Index was outside the bounds of the array.
【堆栈】：at SqlSugar.UpdateableProvider`1.SetColumns(Expression`1 columns)
   at CW.Api.Services.LoginService.EditAccount(String openId, Int32 bay) in D:\work\crazy-workers-net.git\CW.Api\Services\LoginService.cs:line 52
   at CW.Api.Controllers.LoginController.Login(LoginModel model) in D:\work\crazy-workers-net.git\CW.Api\Controllers\LoginController.cs:line 56
   at lambda_method484(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) 
  ResourceInvoker.Next => GlobalExceptionsFilter.OnException => NLogHelper.ErrorLog
2024-09-24 14:57:10.5216 CW.Common.Logs.NLogHelper.ErrorLog Error: 
【描述】：Index was outside the bounds of the array.
【堆栈】：at SqlSugar.UpdateableProvider`1.SetColumns(Expression`1 columns)
   at CW.Api.Services.LoginService.EditAccount(String openId, Int32 bay) in D:\work\crazy-workers-net.git\CW.Api\Services\LoginService.cs:line 59
   at CW.Api.Controllers.LoginController.Login(LoginModel model) in D:\work\crazy-workers-net.git\CW.Api\Controllers\LoginController.cs:line 56
   at lambda_method484(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) 
  ResourceInvoker.Next => GlobalExceptionsFilter.OnException => NLogHelper.ErrorLog
